### PR TITLE
[EDS-553] Configure application for better templating, and refactor Search blueprint for more intuitive behavior

### PR DESCRIPTION
**Pull request by tomthorogood**
Closes EDS-553

There are multiple commits included with this change. The most important one (with the most useful commit message) is https://github.com/UWIT-IAM/uw-husky-directory/commit/624375f045768afb951ec78d24a2c69146cd754f . I recommend reading that grokking that commit above all else. (Although https://github.com/UWIT-IAM/uw-husky-directory/pull/37/commits/19a8a81d62d7b08600cfc01e4138590973cd3796 also shows some of the pre-plumbing that is good to know!)

Check out and run this image with: `./scripts/run-development-server -i uwitiam/husky-directory:commit-c7aeac5f22`

### CODE REVIEW

**Comment by goulter** [comment]
- No NET-ID placeholder?
- Summary is not showing the phone number (using "kurle" as my search)

**Comment by tomthorogood** [comment]
1. We discussed in last week's meeting that we are not going to implement the netid field for security reasons.
2. Thanks, I'll take a look.

**Comment by tomthorogood** [comment]
I'm not sure what you mean:

Screen Shot 2021-02-12 at 1 32 18 PM

**Comment by goulter** [comment]
1. Great, working as expected! I must have missed that part.
2. Search kurle, select name

**Comment by tomthorogood** [comment]
Found the bug, easy fix, adding some tests which is requiring some test refactoring.

**Comment by goulter** [comment]
Awesome!

**Comment by tomthorogood** [comment]
Three new commits. https://github.com/UWIT-IAM/uw-husky-directory/pull/37/commits/d7cb38e4403528e8cf64907598e6061449c98d4a is the important one regarding the bug you found. 

The others do some cleanup and improve the tests to actually ensure content is not being dropped from our renders.

**Comment by tomthorogood** [comment]
NB: The image to check out and test will change, I will update the image name in the description once the workflow completes.

**Comment by tomthorogood** [comment]
Updated the image in the description; feel free to test it out and let me know if i missed anything else!

**Comment by goulter** [comment]
Great, I'll give it a gander.

**Review by goulter — APPROVED** [review]
nice bug fixes and additional niceties

**Pull request merged**
