### PR TITLE
[EDS-563] Support department queries

### PR DESCRIPTION
**Pull request by tomthorogood**
Consists of 2 commits, only the first of which actually does the work to support department queries. The follow-up commit increases code coverage and cleans up some cruft. If you are only interested in reviewing the functional changes, please read that commit on its own. This was a pretty small change by comparison to many others.

### CODE REVIEW

**Review by goulter — COMMENTED** [review]
Just a couple quick observations/questions, these likely aren't show-stoppers :)

This supports department search, but isn't intended to return the department for consumption in the full results on the front end correct? 
I tested/examined the `data` object, didn't see department there, but just want to double check with you.

Another check I did was on the result count. The names in each result are nearly the same. 
Can the 5 additional match results in the new site be attributed to the data source difference or perhaps the is/matches?
The brief check I did was with department = Applied Mathematics
old site:
Department is "Applied Mathematics": 44 Faculty/Staff
Department contains "Applied Mathematics": 9 Faculty/Staff
new site:
Department matches "Applied Mathematics": 49 faculty/staff
Department contains "Applied Mathematics": 9 faculty/staff
I put together a name comparison chart [here](https://docs.google.com/spreadsheets/d/1eAWfx4G2Q24fWb9I9g-lkrcBGdPLl1K9z5wLh3SK9Pw/edit?usp=sharing). I thought it might have been departments with "AMATH" or "ASE" in them, maybe not.

**Comment by tomthorogood** [comment]
> This supports department search, but isn't intended to return the department for consumption in the full results on the front end correct?

Yes, it only supports the query. I don't even know what parts of the UI use this at the moment.

**Comment by tomthorogood** [comment]
Ok, after confirming the behaviors, I agree that the model output should at least be part of this PR, and that the query count diff warrants investigation. Does the following list of action items sound ok? (Again, remembering that we can't be expected to validate every possible data set, but if there's other things you need to try, please let me know!) 

I'll keep this updated to mark the next iteration.

## Action Items

- [ ] Return `department` in output models (investigating the other issue would be easier if the JSON had that... 😂
- [ ] Add a test to determine its inclusion in output models.
- [ ] Investigate data diff to determine whether root cause is a thing that needs to be fixed
-  [ ] If ☝️needs fixing, implement that fix and add a test

**Comment by goulter** [comment]
> Yes, it only supports the query. I don't even know what parts of the UI use this at the moment. I think you have an open Jira for it already? That said, I'll double check it's getting through the translator, you are right that since there is no front-end testing for it yet, we wouldn't catch it if it was getting dropped.

Yup, I have a JIRA to display department on the front end, to be pursued when the data is available :)
I think thats going to be somewhat like the array of phone numbers since a person can have more than one dept.

> we can't be expected to validate every possible data set

for certain!

> but if there's other things you need to try, please let me know

Nothing more at this moment. After the department data is available, I'll compare that data to some of the test people from yesterday, since the was some good in department data there if I recall.

Sounds like we are on the same page. Once ready, I'll look at the data returned, and compare a few user's department data on the new site and old site.

**Comment by tomthorogood** [comment]
Can't you do those comparisons now so that I know everything at once?

**Comment by goulter** [comment]
I don't think I can compare department data between the old and new sites, as I don't have it on the front end. Is there somewhere else I should look?
Cauce's data object:
`{'name': 'Ana Mari Cauce', 'phone_contacts': {'phones': ['+1 206 543-5010'], 'faxes': [], 'voice_mails': [], 'touch_dials': [], 'mobiles': [], 'pagers': []}, 'email': 'president@uw.edu', 'href': 'L2lkZW50aXR5L3YyL3BlcnNvbi84OUQ5NkRGODZBN0MxMUQ1QTRBRTAwMDRBQzQ5NEZGRS9mdWxsLmpzb24='}`
The comparison I can do and did is compare department query count results (see my google doc), not the department data itself.

**Comment by tomthorogood** [comment]
Why do you need to hand-validate department data?

**Comment by tomthorogood** [comment]
I would also like to add that you can (and should) use the PWS API to run these queries. Then you see the actual source data: For example: https://it-wseval1.s.uw.edu/identity/v2/person?department=%2AApplied%20Mathematics%2A&employeeAffiliationState=current&verbose=true

**Comment by goulter** [comment]
Here's what I'm looking for, trying to check the department data i the same, when compared to the old directory, then I can say, yep, looks good, or no, we have an inconsistency :) Not sure we can automate, but here goes...
I was going to do a department query for the following users on both sites and compare them, as these name queries have interesting ORG properties in the VCards in the _old directory_ 
**Jonanthan Pass** 
ORG:University of Washington;Identity and Access Management, UW-IT: ITI: Workforce Strategy & Development
**Jacob Morris**
ORG:University of Washington;Information School
ORG:University of Washington;PRES: Information Technology
**Cauce**
ORG:University of Washington;Gender, Women and Sexuality Studies
ORG:University of Washington;College of Education
ORG:University of Washington;American Ethnic Studies
ORG:University of Washington;Psychology
ORG:University of Washington;University of Washington

**Comment by tomthorogood** [comment]
You can do all of that right now. You have access to the same APIs and the same code base and the same branches that I do. (I mean, not like _right_ now, but I mean, you don't need to wait for me to add a new feature for you to do any analysis you want.)

**Comment by tomthorogood** [comment]
Pending  #52, working on the remaining investigatory action item(s)

**Comment by tomthorogood** [comment]
In reviewing the data associated with the `Applied Mathematics` question above, the "Extra" people all seem legit. I think this is another case where we have to trust our data source. The previous query was doing a match on a string field; PWS is doing something more complex, so probably finds more associated folks. I don't think there's anything to be fixed there.

**Review by goulter — APPROVED** [review]

**Comment by tomthorogood** [comment]
💃🏻

**Pull request merged**
