### PR TITLE
[EDS-556] Supports SAML sign-on to unlock other search options

### PR DESCRIPTION
**Pull request by tomthorogood**
Note: Does **NOT** enable student search yet. The radio buttons won't currently have any effect on the search results.

- When a user visits the page, they are now shown the sign in link in order to see other search options.
- After signing in, they can select other search options
- Fixes the mock idp integration so that it works locally and is testable.
- Adds tests!

You can test these changes with:

```
./scripts/run-development-server.sh -i uwitiam/husky-directory:commit-1ebcfc9854
```

### CODE REVIEW

**Comment by goulter** [comment]
Should clicking the "Sign in for student search" link prompt me? 
I click it and I get the new radio options, after that I do a Faculty/Staff search, and I get my results etc, and right side of the search portion shows the "Sign in for student search" link again without the radios, just like I did when I started my search. Expected?

**Comment by tomthorogood** [comment]
Try it in a private window.

**Comment by tomthorogood** [comment]
It works just like identity.UW; if you're already authenticated, it won't prompt you

**Comment by tomthorogood** [comment]
oh, wait! This is in mock only, no, it won't ever prompt you. The mock IDP always says "come right in"

**Comment by goulter** [comment]
Should I be getting the repeated/second sign on prompt? If thats ok, at least for now, we are good to go.
https://github.com/UWIT-IAM/uw-husky-directory/pull/39#issuecomment-797821778

**Comment by tomthorogood** [comment]
I am not sure what you mean. 

This is a mock IdP that does not do any actual credentialing or authentication. It just pretends to so that we can test all of the paths of our application.

Our website does not have a sign in form. The idp handles it; it's the same form you use every day with other UW services.

**Review by goulter — APPROVED** [review]
That answers my question and makes sense with what I experienced.

**Pull request merged**
